### ISSUE TITLE
Tresoreria/Bestretes: poder activar totes les nòmines previstes tot l'any pq surti pagament esperat a Tresoreria

### ISSUE THREAD

**Issue by zarpilla** [zarpilla/projectes-front#1]
Volem poder crear totes les nómines de cop per tal de que ens apareguin totes a tresoreria enlloc d'anar una per una.

**Comment by zarpilla** [comment]
Ok @JordiEscodaCusido

**Comment by zarpilla** [comment]
@JordiEscodaCusido a l'apartat de Persones, hi ha una nova secció per crear les bestretes de tothom: 

https://projectes.arrandeterra.org/stats/#/working-day


![Image](https://user-images.githubusercontent.com/3697530/212742596-4973eb95-1eac-4c6a-afd0-dd2528d1810e.png)

Si n'hi ha de creades no les sobreescriu, només fa la de les persones i mesos que faltin.

prova-ho i em dius.

**Comment by JordiEscodaCusido** [comment]
perfecte, ho fa bé! tasca tancada! merciiii
