### ISSUE TITLE
Dietes: excel que baixa, falta que baixi columna "quantitat" i columna "preu"

### ISSUE THREAD

**Issue by JordiEscodaCusido** [zarpilla/projectes-front#12]
Dietes: excel que baixa, falta que baixi columna "quantitat" i columna "preu"

**Comment by zarpilla** [comment]
@JordiEscodaCusido hauriem de veure quin format vols pq l'excel és un excel de totals i ara necessites un excel de línies.

**Comment by JordiEscodaCusido** [comment]
no sé si t'he entès, cal que baixi cada línia de cada despesa de dietes on hi consti la columna "data", "concepte" "preu" + lo habitual. Sí?

**Comment by zarpilla** [comment]
No ens hem entés del tot. Ara mateix l'excel és un excel de totals: factures, dietes, altres... i vols un excel de les línies d'aquests. Hem d'acordar el format pq s'entengui

**Comment by JordiEscodaCusido** [comment]
sí, ja ho entenc, el que baixa l'excel de despeses és la despesa total d'aquella despesa que és una dieta. Però hauríem de fer d'alguna manera que baixés les línies pq per declarar el kms (irpf) i els tiquets (iva) que conté les dietes, cal que baixem les línies desglossades de cada dieta, si no el gestor no sap quina part del kms conté irpf dins d'aquella dieta i quina no, m'explico?

**Comment by zarpilla** [comment]
@JordiEscodaCusido fes-li una ullada a l'excel. He combinat capçaleres i línies, jo crec que et valdrà. Ja em dius.

**Comment by JordiEscodaCusido** [comment]
està perfecte! bona feina! tanco aquest tiquet!
