### ISSUE TITLE
Tresoreria: visualització pla de tresoreria 2022! (PROVISIONAL I PRIORITARI)

### ISSUE THREAD

**Issue by JordiEscodaCusido** [zarpilla/projectes-front#15]
Per les proves que estic fent per assegurar que això del pla de tresoreria va bé, necessito visualitzar els mesos de 2022. Ho pots habilitar provisionalment i quan ho tingui quadrat, ho deshabilites (i ja està bé que només es vegi del mes actual en endavant!)??

**Comment by zarpilla** [comment]
@JordiEscodaCusido he creat un paràmetre per fer això, si aquesta és la tresoreria començant a l'any actual

https://projectes.arrandeterra.org/stats/#/tresoreria

podem demanar l'inici d'un altre amb un parèmetre a la URL: 

https://projectes.arrandeterra.org/stats/#/tresoreria?year=2022

**Comment by JordiEscodaCusido** [comment]
resolt i tancat, merci
