### ISSUE TITLE
Tresoreria/Bestretes Pagament de conceptes de nòmines és "SS a càrrec de la cooperativa" + "Altres a càrrec de la treballadora"

### ISSUE THREAD

**Issue by JordiEscodaCusido** [zarpilla/projectes-front#18]
He descobert un error meu al dissenyar una operació que cal esmenar. És fàcil

Actualment, al pagar la nòmina al mòdul Bestretes, es genera un pagament al mòdul "Tresoreria"a més vençut següent (exemple: bestret de gener --> es genera un pagament a 28/02) que és de la part de "SS a càrrec de la cooperativa". Doncs en aquest pagament cal sumar-hi també la part de "Altres a càrrec de la treballadora", que per error posa que es paga amb IRPF a dia 20 de trimestre vençut. Només això.

**Comment by zarpilla** [comment]
fet @JordiEscodaCusido , fes-li una revisió

**Comment by JordiEscodaCusido** [comment]
ep, ho he comprovat i a tresoreria, els moviments de pagament de seg social a mes vençut només contenen el "SS a càrrec de la cooperativa" i no suma la que et demanava, "Altres a càrrec de la treballadora"

i tb veig que hi ha alguna vegada (exemple: Erik nòmina gener22) que l'IRPF d'aquest mes que ha d'aparèixer a Tresoreria22 a 20/04/22 no hi és! La de Erik nòmina febrer22 sí que apareix bé, per exemple....

**Comment by zarpilla** [comment]
pot ser que haguem de refer les nòmines ja fetes, ho reviso

**Comment by zarpilla** [comment]
Hola @JordiEscodaCusido 

he refet les nòmines i crec que ara ho fa bé:

![image](https://user-images.githubusercontent.com/3697530/217330853-2aaa95ca-4b3b-4974-b992-4d5255d14cb9.png)

Aquest concepte (Altres nòmina) és aquest "Altres a càrrec de la treballadora"
