### ISSUE TITLE
Bestretes: he canviat el percentatge de cost de la Seguretat Social a "Strapi --> Quotes --> Me" i no se m'actualitza!

### ISSUE THREAD

**Issue by JordiEscodaCusido** [zarpilla/projectes-front#19]
Bestretes: he canviat el percentatge de cost de la Seguretat Social a "Strapi --> Quotes --> Me" i no se m'actualitza!

**Comment by zarpilla** [comment]
aquest valor és per quan creees nous períodes de "Persones" o si als existents els hi canvies el tipus (autònoma/General). Ja ho fas així @JordiEscodaCusido ?

**Comment by JordiEscodaCusido** [comment]
aquí ok, però on no es canvia és a la despesa de nòmina que es crea a les bestretes, hi ha un % de cost de la seguretat social que no s'ha canviat. Saps on vull dir?

**Comment by zarpilla** [comment]
fet @JordiEscodaCusido , fes-li una revisió

**Comment by JordiEscodaCusido** [comment]
crec que ja ho fa bé. El que no s'ha canviat és el títol de la cel·la, que segueix posant "32,85%" enlloc del nou %.

**Comment by zarpilla** [comment]
algo no està funcionant doncs pq l'hauria de canviar tb, almenys m'ho feia a mi, ho reviso bé

**Comment by zarpilla** [comment]
@JordiEscodaCusido he refet les nòmines de l'Erik (gener, febrer i març) i surt bé:


![Image](https://user-images.githubusercontent.com/3697530/217331311-9020f3eb-412b-4549-8b8b-ffbff6faf9d6.png)

A cada canvi de "Persones" hem d'esborrar-les i refer-les, per això surt el missatget de ojo. Potser podriem refer-les automàticament, aixó sí.

**Comment by JordiEscodaCusido** [comment]
ok, tema tancat doncs, merciii
