### ISSUE TITLE
Despeses/bestretes: Modificació quantitats diverses nòmines

### ISSUE THREAD

**Issue by JordiEscodaCusido** [zarpilla/projectes-front#2]
Al desglòs de les diferents despeses que inclouen les nòmines i que s'estableixen segons uns % predeterminats, cal poder-los modificar manualment per ajustar decimals i que quadrin exactament amb els pagaments a fer a treballadora, Seg Social i Hisenda

**Comment by zarpilla** [comment]
Fet, ara son també documents modificables:



![Image](https://user-images.githubusercontent.com/3697530/212742767-2bd781f3-ef77-4dfc-b6d3-56dbf48025d4.png)

**Comment by zarpilla** [comment]
Fet @JordiEscodaCusido

**Comment by JordiEscodaCusido** [comment]
ara ja no es pot modificar cap de les dues xifres, però la "despesa total", quan canvies alguna xifra anterior sí que s'actualitza, ja ho fa bé, però el "salari net a percebre" no s'actualitza quan modifiques l'IRPF o "altres a càrrec de la treballadora"
(recorda que salari net = salari base - IRPF - altres a càrrec de la treballadora).

**Comment by zarpilla** [comment]
ho reviso!

**Comment by zarpilla** [comment]
fes-li una ullada @JordiEscodaCusido

**Comment by JordiEscodaCusido** [comment]
perfecte, tasca resolta!
