### ISSUE TITLE
Canviar nom Ana per Ana Correro

### ISSUE THREAD

**Issue by ana-arrandeterra** [zarpilla/projectes-front#24]

**Comment by zarpilla** [comment]
fet!

**Comment by ana-arrandeterra** [comment]
Gràcies! Tinc un altre problema. Des de que s'ha canviat el nom, ara haig de posar manualment el meu nom quan vull registrar hores a la pestanya d'Hores dedicades, es podria tornar a posar automàticament el meu nom per estalviar clics?

**Comment by zarpilla** [comment]
Ostres @ana-arrandeterra  , mira de sortir (dalt a la dreta) i tornar a entrar, pq lo de posar el nom manualment ha de funcionar bé
