### ISSUE TITLE
Dietes: establir IRPF automàtic relacionat amb IRPF indicat per bestretes

### ISSUE THREAD

**Issue by JordiEscodaCusido** [zarpilla/projectes-front#3]
IRPF automàtic segons allò determinat en el mes a "Persones" als desplaçaments que incloguin una quantitat superior a 0,19€/km, de 0,20€/km i més (a 0,19€/km i menys el IRPF ha de ser 0%)

**Comment by zarpilla** [comment]
@JordiEscodaCusido els preus que pageu els desplaçaments son sempre els mateixos a dia d'avui? Vull dir si hi ha per dos tipus:

- desplaçament a 0.23€/km
- desplaçament a 0.19€/km

Pq podriem establir tenir dos tipus de "transport":

- Transport 0.23: ens defineix el preu a 0.23 i el irpf a 15%
- Transport 0.19: ens defineix el preu a 0.19 i el irpf a 0%

Si mai aquests 0.23/0.19 canvien els canviem a la taula d'origen.

M'he explicat?

**Comment by JordiEscodaCusido** [comment]
Que jo sàpiga, els desplaçaments de totes les persones d'Adt es paguen a 0,32€/km. Llavors, d'aquests 0,32€, fins a 0,19€ (inclòs) la retenció de IRPF a aplicar és 0%; i a partir d'aquest -de 0,20€ a 0,32€ aquest any a Adt- la retenció que s'ha d'aplicar dIRPF és del % que s'apliqui a la nòmina (com que aquest % el posem a "persones", per això dic que hauria de sortir automàtic).

m'he explicat?

**Comment by zarpilla** [comment]
@JordiEscodaCusido per acabar això, necessito que ompliu una correspondència entre contactes (als que s'asocien les dietes) amb les "Persones" de la cooperativa. He creat un cap a contactes que caldria omplir: 



![Image](https://user-images.githubusercontent.com/3697530/222230359-225902ac-2a5f-439a-8e9e-68bcf3d0b82e.png)

Això em serveix per anar a buscar el seu IRPF que aplicaré a la dieta.

Quan ho tingueu em dius, que mentrestant acabaré i pujaré els canvis a les dietes per a que agafin aquest valor

**Comment by JordiEscodaCusido** [comment]
feeeeeeeeet

**Comment by zarpilla** [comment]
Els canvis pendents a les dietes ja estan pujats, quan estiguin associades les persones i els contactes, em dius i ho provem i t'explico com funciona @JordiEscodaCusido . Básicament caldrà provar que fa quan tenim dietes de persones amb irpf i creem noves línies.

**Comment by zarpilla** [comment]
Si proves d'afegir línies a dietes, les desglossa d'aquesta manera: 

![image](https://user-images.githubusercontent.com/3697530/222437736-1fc09a69-02cc-4617-965a-91cf7c6b2804.png)

Fes alguna prova @JordiEscodaCusido

**Comment by JordiEscodaCusido** [comment]
si jo clico una línia nova, el que veig que fa és desglossar la dieta ja creada entre aquests dos trams de IRPF i ho fa bé, good job! 

ara bé, si vull crear una de nova, només em crea les dues línies desglossades, però com creo la principal, en què li dic quants kms he fet i a quant val el km?

**Comment by zarpilla** [comment]
@JordiEscodaCusido els kms que ha fet s'han de posar a la quantitat, sempre a les dues línies. 

Una és el primer tram sense irpf i la segona és el tram de 0.20 fins a 0.32 amb irpf. Els valors aquests de 0.20 i 0.32 es defineixen des de l'admin per si mai canvien els preus

**Comment by JordiEscodaCusido** [comment]
val ja veig q fa

doncs jo diria q ja està bé i que ho podem donar per tancat! merci!
